baseURL: https://skowalak.github.io/bay/
languageCode: en-us
title: Bay Hugo Theme
themesDir: ../..
theme: bay
permalinks:
  blog: /:year/:month/:day/:title/
outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed
params:
  logo:
    image: true
    text: BAY THEME
  searchEnabled: true
  notShowThemeInfo: false
  contact:
    - name: Email
      value: yourmail@domain.com
      link: mailto:yourmail@domain.com
    - name: WeChat
      value: YourWeChatUsername
      link: "#"
  social:
    - name: Twitter
      link: https://twitter.com/YourTwitterUsername
    - name: Facebook
      link: https://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: https://github.com/YourGitHubUsername
    - name: Dribbble
      link: https://dribbble.com/YourDribbbleUsername
    - name: RSS
      link: feed.xml
  menu:
    - name: Home
      slug: 
    - name: Work
      slug: work
    - name: Blog
      slug: blog

