baseURL: http://example.org/
languageCode: en-us
title: Bay Hugo Theme
themesDir: ../..
theme: bay
permalinks:
  blog: /:year/:month/:day/:title/
outputs:
  home:
    - html
    - RSS
  section:
    - html
outputFormats:
  RSS:
    mediatype: application/rss
    baseName: feed
params:
  notShowThemeInfo: false
  contact:
    - name: Email
      value: yourmail@domain.com
      link: mailto:yourmail@domain.com
    - name: WeChat
      value: YourWeChatUsername
      link: "#"
  social:
    - name: Twitter
      link: http://twitter.com/YourTwitterUsername
    - name: Facebook
      link: http://facebook.com/YourFacebookUsername
    - name: LinkedIn
      link: http://linkedin.com/in/YourLinkedInUsername
    - name: GitHub
      link: http://github.com/YourGitHubUsername
    - name: Dribbble
      link: https://dribbble.com/YourDribbbleUsername
    - name: RSS
      link: /feed.xml
  menu:
    - name: Home
      slug: /
    - name: Work
      slug: /work
    - name: Blog
      slug: /blog

